base_url = "https://darrynpasqua.com"
title = "Darryn Pasqua"
description = "I build fixes for people stuck doing things the hard way."
default_language = "en"
theme = "duckquill"
compile_sass = true
generate_feeds = true
feed_filenames = ["atom.xml"]

[markdown]
highlight_code = true
highlight_theme = "css"

[extra]
default_theme = "dark"
accent_color = "#ff7800"
accent_color_dark = "#ffa348"
bundled_fonts = true
styles = ["gallery.css"]
show_copy_button = true
show_reading_time = true
show_share_button = false
show_backlinks = false
source_url = "https://github.com/dpasqua17/darrynpasqua.com"

[extra.nav]
show_feed = false
show_theme_switcher = true
show_repo = false
links = [
  { url = "mailto:dpasqua@bullpencoach.us", name = "Email" },
  { url = "https://github.com/dpasqua17", name = "GitHub" },
  { url = "https://linkedin.com/in/darrynpasqua", name = "LinkedIn" },
]

[extra.footer]
show_copyright = true
show_powered_by = true
show_source = false
links = [
  { url = "mailto:dpasqua@bullpencoach.us", name = "Email" },
  { url = "https://github.com/dpasqua17", name = "GitHub" },
  { url = "https://linkedin.com/in/darrynpasqua", name = "LinkedIn" },
]
